FROM mongo:latest

MAINTAINER <Gearoid, Romero> contact@bejanalex.com

ENV AUTH yes
ENV STORAGE_ENGINE wiredTiger
ENV JOURNALING yes

#
#ADD internal-run.sh /internal-run.sh
#RUN chmod a+x /internal-run.sh
#
#ADD set_mongodb_password.sh /set_mongodb_password.sh
#RUN chmod a+x /set_mongodb_password.sh
#
#ENTRYPOINT ["/internal-run.sh"]